### ISSUE TITLE
Move railcore.org wiki to github

### ISSUE THREAD

**Issue by lostapathy** [railcore/railcore.github.io#2]
Migrating railcore.org from a wiki-backed site to GitGub has been discussed on Facebook and IRC.  This post seeks to develop a plan to actually get that done.

I believe there is consensus to convert the site to use [GitHub Pages](https://pages.github.com/) rather than a wiki, for various reasons.  Primarily, to stop vandalism, but also to centralize all Railcore data and contributions in one place/platform/workflow.

Steps to move forward:

- [x]  **1.  Rename this repo as railcore.github.io** Github will then host the gh_pages branch at http://railcore.github.io

- [x]  **2.  Add Jekyll configuration to the repo** Github pages uses [Jekyll](https://jekyllrb.com) to generate pages.  We'll need to add that configuration to the repo and configure it for development/contribution.

- [x]   **3.  Pick a Jekyll Theme for the site** I suggest we settle on one of the [supported themes](https://pages.github.com/themes/) just in the name of simplicity and ease of getting going.

- [x]  **4.  Update existing content for jekyll** We will probably want to reformat and reorganize the existing content somewhat to work better with GitHub Pages

- [x]  **5.  Import wiki content from railcore.org** There appears to only be about 30 pages of actual content on the wiki, so we can probably just move it by hand and clean up the formatting as volunteer effort allows.''

- [x]  **6.  Setup railcore.org as a custom domain with GitHub pages** Once railcore.github.io is working as desired, we can setup both GitHub pages and DNS for railcore.org to point to the new page

- [ ]  **7.  Establish contributing guidelines for the site** Once we are over the hump with this, we should establish guidelines for how to organize pages on the site.  In particular, how/where to post user-specific content such as mods or build logs.

**Comment by dandancheeseandham** [comment]
Happy to help with no 5, let me know when you're ready for content to be moved.

**Comment by natewalck** [comment]
3. I like Slate the best, with Minimal as a fallback.

**Comment by lostapathy** [comment]
I like the feel of Slate as well, although there might be merit to [Architect](https://pages-themes.github.io/architect/) since is has a sidebar we can use for navigation?

**Comment by natewalck** [comment]
This one looks nice too: https://github.com/poole/lanyon

**Comment by natewalck** [comment]
Or this: https://github.com/fongandrew/hydeout

**Comment by lostapathy** [comment]
On #3, I went with hydeout for the theme.  Mostly because the title font in the sidebar seemed closest to the font in the logo @jstevewhite designed.

Note also that this repo was renamed from documentation to railcore.github.io so that it can be an organization site at https://railcore.github.io/

**Comment by dandancheeseandham** [comment]
Nice work @lostapathy , I like the look.

> I believe there is consensus to convert the site to use [GitHub Pages](https://pages.github.com/) rather than a wiki, for various reasons. Primarily, to stop vandalism, but also to centralize all Railcore data and contributions in one place/platform/workflow.

I may have misunderstood, we're not using Github wiki **at all**?

There are approaches I can see here, and I'd just like to check and clarify our way forward.

1) Use Github Pages for everything.
2) Use Github Pages for simple website, and use the Github wiki for the majority of the documentation.

I guess I'd assumed (2), and I just want to check I'm not the only one that got the wrong end of the stick :)

And if (1) is the workflow going to be similar? 
While I use Windows & Linux, I spend the majority of my time Windows side and I can't be bothered to run Jekyll for a proving ground, and updating documentation via pull requests and having third parties check will slow things down a lot when it comes to formatting checks and changes... (unless I use the wiki with it's Markdown interpreter as the "proving ground" first before going with a commit)

**Comment by dandancheeseandham** [comment]
I realise I could start set up  use my own Github wiki for the first drafts... So ignore last comment :)

**Comment by natewalck** [comment]
The whole point of github is having people check before landing :) It’s less efficient to land and then have to change stuff later. 
Markdown is pretty easy to read once you get an idea of what the markdown looks like rendered in Jekyll. Ideally you would work on the repo on your one fork and make a PR to get the changes merged in. 
Nate
    	
    	

    	
    
  




On Thu, Feb 21, 2019 at 8:18 AM -0500, "Dan White" <notifications@github.com> wrote:












I realise I could start set up  use my own Github wiki for the first drafts... So ignore last comment :)

**Comment by dandancheeseandham** [comment]
5. is done I believe.

Also I noticed yesterday that this project is private, so people can't see the members, see anything about the project, nor join easily AFAIK (and sensille was asking about how to join too)

**Comment by lostapathy** [comment]
Setting visibility is opt-in per-member of the project.  You can go to https://github.com/orgs/railcore/people and make yourself public if you want, but I don't believe that's something we can globally disclose for everyone.

As far as joining - you don't need to be a member in order to submit a PR, that's the beauty of github - anyone can just contribute.

**Comment by psych0d0g** [comment]
railcore.org setup as 301 redirect for now, gonna work on the complete custom domain next

**Comment by psych0d0g** [comment]
dns change has ben requested from domain provider, once done anyone can set railcore.org as custom domain and enable https

**Comment by lostapathy** [comment]
Thanks @psych0d0g !  I will check in on the custom domain and https later today.

**Comment by psych0d0g** [comment]
added custom domain, altough the ssl might take a while and in between the site will be unreachable since ive ben running hsts on the old wiki which enforces https. so whoever visited railcore.org in the past wont be able to access the github wiki right now unless they would completely wipe their browsers cache, "new" users should be using plain http as long as the cert hasnt ben issued by github.

**Comment by lostapathy** [comment]
I took the CNAME file out of the repo, for now, in attempt to get railcore.github.io back to working until DNS for railcore.org propogates.  That way (in theory) railcore.github.io will work again.

Once DNS propogates (looks like 24 hour TTL) I will put the CNAME file back into the repo.

**Comment by psych0d0g** [comment]
i would advise not to, github has no protection whatsoever for domain stealing once configured in DNS, so basically ANYONE could map his github page to railcore.org right now as long as it isnt configured here, and once this happened you cant add the domain here anymore

**Comment by lostapathy** [comment]
https://railcore.org now points directly to the github pages site - thanks all.

**Comment by lostapathy** [comment]
I think it's time to call this complete and close it.  If more user-specific contributions start to become a thing we can do more with guidelines for them.  For now it doesn't appear we need such guidelines.
